import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [input,setInput]=useState("");
  const [fetchImg,setFetchImg]=useState("");
  const [err,setErr]=useState("")
  const [fetchFlprice,setFetchFlprice]=useState("");
  const [loading,setLoading]=useState(0)
useEffect(()=>{
setLoading(0)
},[])
  const fetchFlp=async()=>{
    setLoading(1)

    setTimeout(async()=>{


var requestOptions = {
//   headers:{

//     "Access-Control-Allow-Origin" : "*", 
// "Access-Control-Allow-Credentials" : true ,
// "Content-Type": "application/json",
//   },
//   mode:'no-cors',
  method: 'GET',
  redirect: 'follow'
};

fetch(`https://api-mainnet.magiceden.dev/v2/collections/${input.toLowerCase().replace(/ /g,"_")}/stats`, requestOptions)
// fetch(`https://api.coralcube.io/v1/getCollections?offset=0&page_size=20&name=${input.toLowerCase().replace(/ /g,"_")}`,requestOptions)
  .then(response => response.json())
  .then(result => {console.log(result);setFetchFlprice(result.floorPrice)})
  .catch(error => setErr(error));

}
    )}
  function removeSpace(str)
  {
     str = str.replace(/\s/g,'')
     setInput(str.toLowerCase());
     console.log(str.toLowerCase())
 }
useEffect(()=>{
  setFetchFlprice("")
  setInput("")
},[])
  return (
    <>
      <Head>
        <title>\</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='container'>
          <div>
            <span className='note'>Enter name of the NFT</span>
          </div>
          <div className='btnContainer'>
          <input className='inputField' name='input' 
            onKeyDown={event => {
              if (event.key === 'Enter') {
                fetchFlp()
              }
            }}
          onChange={(e)=>setInput(e.target.value) } value={input}></input>
           <button className='fetchBtn' onClick={()=>{fetchFlp();}}>
            Click
           </button>
          </div>
          <div  className='imgContainer'>
            {
               fetchFlprice ?
              <>
            <div>
             
              <h1 className='result'>
              Floor price:&nbsp;{fetchFlprice/1000000000}&nbsp;SOL

              </h1>
            </div>
              </>
              :
              <div>
             
              <h3 className='result'>
             

              </h3>
            </div>
            }
        

          </div>
        </div>

      </main>
    </>
  )
}
