import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [input,setInput]=useState("");
  const [fetchImg,setFetchImg]=useState("");

  const [fetchFlprice,setFetchFlprice]=useState("");
  const [loading,setLoading]=useState(0)

  const fetchFlp=async()=>{
    setTimeout(async()=>{
      setLoading(1)
//       headers:{
//         "Access-Control-Allow-Origin" : "*", 
// "Access-Control-Allow-Credentials" : true ,
// "Content-Type": "application/json",
//       }
var requestOptions = {
  // method: 'GET',
  // redirect: 'follow',
  mode:'no-cors',

};
      const response = await fetch(`https://api-devnet.magiceden.dev/v2/collections/degods/stats`,
      
);
      var data =  response;
      console.log(data);
      // setFetchImg(data.collection.banner_image_url);
      // setFetchFlprice(data.collection.stats.floor_price)
    },2000)

  }
  function removeSpace(str)
  {
     str = str.replace(/\s/g,'')
     setInput(str.toLowerCase());
     console.log(str.toLowerCase())
 }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='container'>
          <div>
            <span className='note'>Enter slug name of the NFT</span>
          </div>
          <div className='btnContainer'>
          <input className='inputField' name='input' 
            onKeyDown={event => {
              if (event.key === 'Enter') {
                fetchFlp()
              }
            }}
          onChange={(e)=>setInput(e.target.value) } value={input}></input>
           <button className='fetchBtn' onClick={()=>{fetchFlp();}}>
            Click
           </button>
          </div>
          <div  className='imgContainer'>
            {
              fetchImg ?
              <>
                  <img src={fetchImg} alt='' className='fetchImg' />
            <div>
             
              <h1 className='result'>
              Floor price:&nbsp;{fetchFlprice}

              </h1>
            </div>
              </>
              :
              <h2 className='note'></h2>
            }
        

          </div>
        </div>

      </main>
    </>
  )
}
